-- Clean up problematic triggers if they exist
DROP TRIGGER IF EXISTS on_record_delete ON records;
DROP TRIGGER IF EXISTS on_record_update ON records;
DROP FUNCTION IF EXISTS delete_storage_object();

-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY, -- Line userId
    display_name TEXT,
    picture_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create records table
CREATE TABLE IF NOT EXISTS records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order" INTEGER,
    name TEXT,
    email TEXT,
    keyword TEXT,
    file_url TEXT,
    file_id TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE records ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid "already exists" errors
DROP POLICY IF EXISTS "Allow public read/write for users" ON users;
DROP POLICY IF EXISTS "Allow public read/write for records" ON records;

CREATE POLICY "Allow public read/write for users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write for records" ON records FOR ALL USING (true) WITH CHECK (true);

-- --- STORAGE SETUP ---
-- 1. Create a bucket named 'files'
INSERT INTO storage.buckets (id, name, public) VALUES ('files', 'files', true) ON CONFLICT (id) DO NOTHING;

-- 2. Set up Storage Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload" ON storage.objects;
DROP POLICY IF EXISTS "Public Update" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'files');
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'files');
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'files');
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'files');
